name: Fennel CI

on:
  workflow_dispatch:
  push:
    paths:
      - "typed/fnl.runtime/**"
      - ".github/workflows/fennel-ci.yml"
  pull_request:
    paths:
      - "typed/fnl.runtime/**"
      - ".github/workflows/fennel-ci.yml"

env:
  CLOJURE_CLI_VERSION: "1.12.0.1530"

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Update package list
        run: sudo apt-get update

      - name: Install Lua
        run: sudo apt-get install -y lua5.3

      - uses: DeLaGuardo/setup-clojure@13.4
        with:
          cli: ${{env.CLOJURE_CLI_VERSION}}

      - name: Make script executable
        run: chmod +x typed/fnl.runtime/script/test

      - name: Run tests
        run: cd typed/fnl.runtime && ./script/test
